# Generated by Django 3.1.1 on 2020-11-17 12:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmother', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
