# Generated by Django 3.1.1 on 2020-10-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmother', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table=None,
        ),
    ]
