# Generated by Django 3.1.1 on 2020-11-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmother', '0002_auto_20201117_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
