# Generated by Django 3.1.1 on 2020-10-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.BOTMOTHER_CHAT_MODEL),
        ('botmother', '0002_auto_20201029_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.BOTMOTHER_CHAT_MODEL),
        ),
    ]
